# Generated by Django 5.0 on 2023-12-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_notifications_newnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnotifications',
            name='title',
            field=models.CharField(default='Welcome Investor', max_length=100),
        ),
    ]
