# Generated by Django 5.0 on 2023-12-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnotifications',
            name='message',
            field=models.TextField(default='Thank you for joining us. Should you have any questions or concerns, kindly open a chat and an admin will be assigned to you.'),
        ),
    ]
