# Generated by Django 5.0 on 2024-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='CanWithraw',
            field=models.BooleanField(default=False),
        ),
    ]
