# Generated by Django 5.0 on 2024-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_accountinfo_canwithraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='message2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
