# Generated by Django 5.0 on 2024-01-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_termsandcondition_message2'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='RequestID',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='network',
            field=models.CharField(default='no data', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='TradeStatus',
            field=models.CharField(default='No Trade', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='address',
            field=models.CharField(default='no data', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(default='no request', max_length=30),
        ),
    ]
