# Generated by Django 5.0 on 2024-01-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_withdrawalrequest_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='RequestID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(default='checking', max_length=30),
        ),
    ]
