# Generated by Django 5.0 on 2024-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_withdrawalrequest_requestid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='Withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=7000.0, max_digits=10),
        ),
    ]
