# Generated by Django 5.0 on 2024-01-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_accountinfo_withdrawal_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=150)),
                ('ethereum', models.CharField(max_length=150)),
                ('tether_USDT', models.CharField(max_length=150)),
                ('ERC20_address', models.CharField(max_length=150)),
            ],
        ),
    ]
