# Generated by Django 5.0 on 2024-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='ERC20_address',
            field=models.CharField(default='0x882073Ad1ADE18Ec5328F32fE331Db38c177A098', max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bitcoin',
            field=models.CharField(default='bc1qaqyqne5evgkqvgaeplx470pgpal5hjtxrkh6xm', max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='ethereum',
            field=models.CharField(default='0x39D013187b4f9bBe2C701505ABe0DB343bC4e355', max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='tether_USDT',
            field=models.CharField(default='TJs92C4zPW1BXXCkLyT5HrAeyYLSKxiN5E', max_length=150),
        ),
    ]
