# Generated by Django 5.0 on 2024-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_walletaddress_erc20_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaddress',
            name='ERC20_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bitcoin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='ethereum',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='tether_USDT',
            field=models.CharField(max_length=150),
        ),
    ]
