# Generated by Django 5.0 on 2024-01-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_walletaddress_erc20_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepositAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Network', models.CharField(max_length=100)),
                ('Proof', models.ImageField(upload_to='payments/')),
                ('Confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
