# Generated by Django 5.0 on 2024-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='not_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
