# Generated by Django 5.0 on 2024-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_deposit_not_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='No Deposit', max_length=50),
        ),
    ]
