# Generated by Django 5.0 on 2024-01-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_deposit_not_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='requestID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
