# Generated by Django 5.0 on 2024-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_deposit_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='requestID',
            field=models.CharField(default='', max_length=8),
        ),
    ]
