# Generated by Django 5.0 on 2024-01-07 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_deposit_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
