# Generated by Django 5.0 on 2024-01-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_deposit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='us_status',
            field=models.CharField(default='Not verified', max_length=50),
        ),
    ]
