# Generated by Django 5.0 on 2024-01-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_customuser_us_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='us_status',
        ),
    ]
