# Generated by Django 5.0 on 2024-01-10 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_customuser_us_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
