# Generated by Django 5.0 on 2024-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_idme'),
    ]

    operations = [
        migrations.AddField(
            model_name='idme',
            name='status',
            field=models.CharField(default='Awaiting', max_length=50),
        ),
    ]
