# Generated by Django 5.0 on 2024-01-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_idme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='idme',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
