# Generated by Django 5.0 on 2024-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_idme_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idme',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Awaiting', max_length=50),
        ),
    ]
