# Generated by Django 5.0 on 2024-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_idme_status_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='verificationStatus',
            field=models.CharField(default='Awaiting', max_length=50),
        ),
    ]
