# Generated by Django 5.0 on 2024-01-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_customuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='verificationStatus',
            field=models.CharField(blank=True, default='Awaiting', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idme',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
