# Generated by Django 5.0 on 2024-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_clientmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='TradeStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Paused', 'Paused')], default='No Trade', max_length=30),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='verificationStatus',
            field=models.CharField(blank=True, choices=[('no-trade', 'No Trade'), ('Awaiting', 'Awaiting'), ('Failed', 'Failed'), ('Verified', 'Verified')], default='Awaiting', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('Invalid', 'Invalid'), ('Failed', 'Failed'), ('Confirmed', 'Confirmed'), ('Credited', 'Credited')], default='No Deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Under review', 'Under review'), ('Failed', 'Failed'), ('pending', 'Approved, Pending')], default='checking', max_length=30),
        ),
    ]
