# Generated by Django 5.0 on 2024-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_customuser_bio_remove_customuser_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='TradeStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Paused', 'Paused'), ('No Trade', 'No Trade')], default='No Trade', max_length=30),
        ),
    ]
