# Generated by Django 5.0 on 2024-02-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_accountinfo_tradestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='verificationStatus',
            field=models.CharField(blank=True, choices=[('Awaiting', 'Awaiting'), ('Failed', 'Failed'), ('Verified', 'Verified')], default='Awaiting', max_length=50, null=True),
        ),
    ]
