# Generated by Django 5.0 on 2024-02-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_accountinfo_verificationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
