# Generated by Django 5.0 on 2024-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='Bonus',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
    ]
