# Generated by Django 5.0 on 2024-02-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_accountinfo_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='Bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='Deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='Profits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='Withdrawal_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=7000.0, max_digits=10, null=True),
        ),
    ]
