# Generated by Django 5.0 on 2024-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_accountinfo_bonus_alter_accountinfo_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='DepositAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='Network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='Proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='requestID',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('No deposit', 'No Deposit'), ('Invalid', 'Invalid'), ('Failed', 'Failed'), ('Confirmed', 'Confirmed'), ('Credited', 'Credited')], default='No Deposit', max_length=50),
        ),
    ]
