# Generated by Django 5.0 on 2024-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_deposit_depositamount_alter_deposit_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='verificationStatus',
            field=models.CharField(blank=True, choices=[('Under review', 'Under Review'), ('Awaiting', 'Awaiting'), ('Failed', 'Failed'), ('Verified', 'Verified')], default='Awaiting', max_length=50, null=True),
        ),
    ]
