# Generated by Django 5.0 on 2024-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_accountinfo_verificationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='DepositAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
