# Generated by Django 5.0 on 2024-02-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_deposit_depositamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('No deposit', 'No Deposit'), ('Invalid', 'Invalid'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed'), ('Credited', 'Credited')], default='', max_length=50),
        ),
    ]
