# Generated by Django 5.0 on 2024-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Paid', 'Paid'), ('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved, Pending', 'Approved, Pending')], default='Checking', max_length=30),
        ),
    ]
